Identityyy/Controllers/accontController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Identityyy.Models;
using System.Security.Claims;

namespace Identityyy.Controllers
{
    [AllowAnonymous]
    public class accontController : Controller
    {
        mainDBcontect context = new mainDBcontect();
        // GET: accont
        [HttpGet]
        [HandleError(View = "Error")]
        
        public ActionResult register()
        {
            return View();
        }
        public ActionResult register(reg user)
        {
            if(ModelState.IsValid)
            {
                context.regs.Add(user);
                context.SaveChanges();
                var identity = new ClaimsIdentity(new List<Claim>()
                {
                    new Claim(ClaimTypes.Name,user.fullname),
                    new Claim("password",user.password)
                }, "ApplicationCookie");
                var ctx = Request.GetOwinContext();
                var autTh = ctx.Authentication;
                autTh.SignIn(identity);
                return RedirectToAction("Index", "booklist");
            }
            return View();
        }
        [HttpGet]

        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult login(reg model)
        {
           // if(ModelState.IsValid)
            //{
                var query = from sure in context.regs
                            where sure.password == model.password
                            select sure;
                if(query!=null)
                {
                    var identity = new ClaimsIdentity(new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name,model.fullname),
                        new Claim("password",model.password)
                    }, "ApplicationCookie");
                    var ctx = Request.GetOwinContext();
                    var auth = ctx.Authentication;
                    auth.SignIn(identity);
                    return RedirectToAction("Index", "booklist");
                }
                return View();
            //}else
            //return View();
        }
        public ActionResult logout()
        {
            var ctx = Request.GetOwinContext();
            var autTh = ctx.Authentication;
            autTh.SignOut("ApplicationCookie");
            return RedirectToAction("login");
        }
    }
}

Identityyy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("log out", "logout", "accont")</li>

                    }els
                    {
                    <li>@Html.ActionLink("register", "register", "accont")</li>

                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="jumbotron">
            <img src="~/Content/images/1.jpg" style="width:100%;height:300px"  />
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>